on: [push]

jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data üì¶
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: https://4g5tw1k0.api.sanity.io/v2021-03-25/data/query/production?query=*%5B_type%20%3D%3D%20%24type%5D%7B%0A%20%20title%2C%0A%20%20_id%2C%0A%20%20%22methodId%22%3A%20slug.current%2C%0A%20%20%22inputs%22%3A%20transputReference.inputsReference%5B%5D-%3E%7B%0A%20%20%20%20prefLabel%2C%0A%20%20%20%20%22inputId%22%3A%20conceptId.current%0A%20%20%7D%2C%0A%20%20%22outputs%22%3A%20transputReference.outputReference%5B%5D-%3E%7B%0A%20%20%20%20prefLabel%2C%0A%20%20%20%20%22outputId%22%3A%20conceptId.current%0A%20%20%7D%0A%7D&%24broader=%22transputTaxonomy_Recommendation%22&%24pageSlug=%22card-sorting%22&%24type=%22method%22
          CONFIGURATION: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.SANITY_ACTIONS_TOKEN }}"} }'
      - name: Print out data
        run: echo "Data retrieved is $FETCH_API_DATA"
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: fetch-api-data-action/data.json
      - uses: actions/checkout@v2
        name: Checkout Branch
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          who-to-greet: 'Marvin the fierce'
          sanity-data: ${{env.FETCH_API_DATA}}
      - name: Print out data
        run: echo "Data retrieved is ${{ env.FETCH_API_DATA }}"
      # Use the output from the `hello` step¬©œÄ¬©œÄÀù‚àè
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Upload text file
        uses: actions/upload-artifact@v2
        with:
          name: output-text-file
          path: createdFile.txt
